import { analyzeSentiment } from "@/lib/sentiment";
import type { Comment, VideoInfo } from "@/types";

export const MOCK_VIDEO: VideoInfo = {
  id: "dQw4w9WgXcQ",
  title: "Como crescer no YouTube em 2026 — estratégias que realmente funcionam",
  channelName: "Canal Criador Pro",
  channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=CCP&backgroundColor=ef4444",
  thumbnailUrl: "https://images.unsplash.com/photo-1611162617474-5b21e939e113?w=640&h=360&fit=crop",
  commentCount: 68,
  viewCount: 284_500,
  publishedAt: "2026-02-15T10:00:00Z",
};

const RAW_COMMENTS: Omit<Comment, "sentiment">[] = [
  {
    id: "1",
    author: "Ana Silva",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    text: "Conteúdo excelente! Finalmente alguém explica de forma clara como crescer no YouTube. Já apliquei 3 dicas e meu CTR subiu 40%.",
    likes: 342,
    publishedAt: "2026-02-15T14:22:00Z",
    replyCount: 12,
    authorReplied: true,
  },
  {
    id: "2",
    author: "Pedro Games",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro",
    text: "Qual ferramenta você usa para editar as thumbnails? Estou começando agora e não sei por onde começar.",
    likes: 89,
    publishedAt: "2026-02-15T15:10:00Z",
    replyCount: 5,
    authorReplied: true,
  },
  {
    id: "3",
    author: "Lucas Tech",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    text: "Vídeo péssimo, puro clickbait. Prometeu estratégias e só falou o básico que todo mundo já sabe.",
    likes: 23,
    publishedAt: "2026-02-15T16:45:00Z",
    replyCount: 8,
    authorReplied: false,
  },
  {
    id: "4",
    author: "Mariana Vlogs",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mariana",
    text: "Amei a parte sobre SEO de título! Nunca tinha pensado em usar o Google Trends assim. Obrigada demais 🙏",
    likes: 156,
    publishedAt: "2026-02-16T09:30:00Z",
    replyCount: 3,
    authorReplied: true,
  },
  {
    id: "5",
    author: "Carlos Editor",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    text: "Quanto tempo leva em média para um canal novo começar a monetizar seguindo essas estratégias?",
    likes: 67,
    publishedAt: "2026-02-16T11:15:00Z",
    replyCount: 4,
    authorReplied: true,
  },
  {
    id: "6",
    author: "Julia Criativa",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Julia",
    text: "Canal incrível! Assisto todos os vídeos. Você poderia fazer um sobre como editar no CapCut?",
    likes: 98,
    publishedAt: "2026-02-16T14:00:00Z",
    replyCount: 2,
    authorReplied: false,
  },
  {
    id: "7",
    author: "Rafael Prod",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rafael",
    text: "Enrolação total. 20 minutos de vídeo para dizer 'poste com consistência'. Perda de tempo.",
    likes: 45,
    publishedAt: "2026-02-16T18:30:00Z",
    replyCount: 15,
    authorReplied: false,
  },
  {
    id: "8",
    author: "Beatriz Marketing",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Beatriz",
    text: "Parabéns pelo conteúdo de qualidade! A dica sobre Shorts como funil de conversão foi genial.",
    likes: 201,
    publishedAt: "2026-02-17T08:00:00Z",
    replyCount: 6,
    authorReplied: true,
  },
  {
    id: "9",
    author: "Thiago Iniciante",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Thiago",
    text: "Tenho 50 inscritos. Vale a pena investir em equipamento caro agora ou foco no conteúdo?",
    likes: 34,
    publishedAt: "2026-02-17T10:45:00Z",
    replyCount: 7,
    authorReplied: true,
  },
  {
    id: "10",
    author: "Fernanda Lifestyle",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fernanda",
    text: "Simplesmente o melhor vídeo sobre YouTube que já vi em português. Compartilhei com toda minha equipe!",
    likes: 278,
    publishedAt: "2026-02-17T13:20:00Z",
    replyCount: 9,
    authorReplied: true,
  },
  {
    id: "11",
    author: "Diego Streamer",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diego",
    text: "Funciona para canal de games também ou só para nichos educativos?",
    likes: 41,
    publishedAt: "2026-02-17T16:00:00Z",
    replyCount: 3,
    authorReplied: true,
  },
  {
    id: "12",
    author: "Camila Coach",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Camila",
    text: "Conteúdo top demais! Me ajudou muito a reorganizar minha estratégia de conteúdo para 2026.",
    likes: 112,
    publishedAt: "2026-02-18T07:30:00Z",
    replyCount: 1,
    authorReplied: false,
  },
  {
    id: "13",
    author: "Gustavo Hater",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Gustavo",
    text: "Horrível. Esse cara só repete o que os gringos falam. Nada original. Nunca mais assisto.",
    likes: 12,
    publishedAt: "2026-02-18T09:15:00Z",
    replyCount: 22,
    authorReplied: false,
  },
  {
    id: "14",
    author: "Patricia SEO",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia",
    text: "A estratégia de palavras-chave de cauda longa é ouro puro. Implementei e já apareço na 2ª página do Google.",
    likes: 189,
    publishedAt: "2026-02-18T11:00:00Z",
    replyCount: 4,
    authorReplied: true,
  },
  {
    id: "15",
    author: "Bruno Filmmaker",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bruno",
    text: "Você usa algum software específico para analisar métricas de retenção além do YouTube Studio?",
    likes: 56,
    publishedAt: "2026-02-18T14:30:00Z",
    replyCount: 2,
    authorReplied: true,
  },
  {
    id: "16",
    author: "Larissa Beauty",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Larissa",
    text: "Adorei! Meu canal de beleza cresceu 200 inscritos na última semana depois de seguir suas dicas de thumbnail.",
    likes: 167,
    publishedAt: "2026-02-19T08:45:00Z",
    replyCount: 5,
    authorReplied: true,
  },
  {
    id: "17",
    author: "Marcos Dev",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcos",
    text: "Fraco demais. Poderia ter aprofundado mais na parte de analytics. Ficou superficial.",
    likes: 18,
    publishedAt: "2026-02-19T10:20:00Z",
    replyCount: 3,
    authorReplied: false,
  },
  {
    id: "18",
    author: "Isabela Music",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabela",
    text: "Como faço para aparecer na aba Shorts sem perder a qualidade do conteúdo longo?",
    likes: 73,
    publishedAt: "2026-02-19T12:00:00Z",
    replyCount: 6,
    authorReplied: true,
  },
  {
    id: "19",
    author: "Renato Finanças",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Renato",
    text: "Sensacional! Já estou aplicando a estratégia de colaborações. Primeira parceria confirmada graças a você!",
    likes: 134,
    publishedAt: "2026-02-19T15:30:00Z",
    replyCount: 8,
    authorReplied: true,
  },
  {
    id: "20",
    author: "Vanessa Food",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vanessa",
    text: "Canal de culinária se beneficia dessas estratégias? Meu nicho parece saturado.",
    likes: 29,
    publishedAt: "2026-02-20T09:00:00Z",
    replyCount: 4,
    authorReplied: true,
  },
  {
    id: "21",
    author: "André Fitness",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Andre",
    text: "Show de bola! A parte sobre primeiros 30 segundos mudou completamente minha retenção.",
    likes: 95,
    publishedAt: "2026-02-20T11:30:00Z",
    replyCount: 2,
    authorReplied: false,
  },
  {
    id: "22",
    author: "TrollMaster99",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Troll",
    text: "Lixo lixo lixo. Canal pequeno dando palpite. Vai trabalhar.",
    likes: 5,
    publishedAt: "2026-02-20T13:00:00Z",
    replyCount: 18,
    authorReplied: false,
  },
  {
    id: "23",
    author: "Helena Educação",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Helena",
    text: "Perfeito para quem está começando! Salvei na playlist de referências. Obrigada pelo esforço!",
    likes: 145,
    publishedAt: "2026-02-20T16:15:00Z",
    replyCount: 3,
    authorReplied: true,
  },
  {
    id: "24",
    author: "Felipe Automacao",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felipe",
    text: "Existe alguma ferramenta gratuita para agendar posts no YouTube como no Instagram?",
    likes: 62,
    publishedAt: "2026-02-21T08:30:00Z",
    replyCount: 5,
    authorReplied: true,
  },
  {
    id: "25",
    author: "Carolina Travel",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carolina",
    text: "Maravilhoso conteúdo! Me inspirou a voltar a postar depois de 6 meses parada.",
    likes: 88,
    publishedAt: "2026-02-21T10:00:00Z",
    replyCount: 1,
    authorReplied: false,
  },
  {
    id: "26",
    author: "João Pet",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Joao",
    text: "Canal de pets funciona com essas estratégias? Tenho 2k inscritos e estou estagnado.",
    likes: 37,
    publishedAt: "2026-02-21T12:45:00Z",
    replyCount: 3,
    authorReplied: true,
  },
  {
    id: "27",
    author: "Amanda Design",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
    text: "A dica de usar contraste nas thumbnails foi a melhor. Meu CTR dobrou em 2 semanas!",
    likes: 176,
    publishedAt: "2026-02-21T15:00:00Z",
    replyCount: 7,
    authorReplied: true,
  },
  {
    id: "28",
    author: "Ricardo Critic",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ricardo",
    text: "Decepcionante. Esperava algo mais avançado. Isso é básico demais para quem já tem canal.",
    likes: 31,
    publishedAt: "2026-02-22T09:30:00Z",
    replyCount: 11,
    authorReplied: false,
  },
  {
    id: "29",
    author: "Natália Parenting",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Natalia",
    text: "Qual a frequência ideal de postagem para um canal pequeno? 1x por semana ou 3x?",
    likes: 52,
    publishedAt: "2026-02-22T11:00:00Z",
    replyCount: 4,
    authorReplied: true,
  },
  {
    id: "30",
    author: "Eduardo Crypto",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eduardo",
    text: "Incrível! Compartilhei no meu grupo de Telegram. Conteúdo de altíssima qualidade.",
    likes: 123,
    publishedAt: "2026-02-22T14:20:00Z",
    replyCount: 2,
    authorReplied: false,
  },
  {
    id: "31",
    author: "Paula Idiomas",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Paula",
    text: "Você recomenda fazer vídeos em inglês também ou focar 100% no público brasileiro?",
    likes: 44,
    publishedAt: "2026-02-22T16:00:00Z",
    replyCount: 6,
    authorReplied: true,
  },
  {
    id: "32",
    author: "HaterAnonymous",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hater",
    text: "Spam de guru. Vende curso no final do vídeo? Aposto que sim. Enganoso.",
    likes: 8,
    publishedAt: "2026-02-23T08:00:00Z",
    replyCount: 25,
    authorReplied: false,
  },
  {
    id: "33",
    author: "Sofia Art",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
    text: "Fantástico! A estratégia de community posts me trouxe 500 novos inscritos em um mês.",
    likes: 198,
    publishedAt: "2026-02-23T10:30:00Z",
    replyCount: 5,
    authorReplied: true,
  },
  {
    id: "34",
    author: "Leandro Review",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Leandro",
    text: "Bom conteúdo, mas a edição poderia ser mais dinâmica. Às vezes fica monótono.",
    likes: 27,
    publishedAt: "2026-02-23T13:15:00Z",
    replyCount: 2,
    authorReplied: false,
  },
  {
    id: "35",
    author: "Tatiane DIY",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tatiane",
    text: "Como você faz para manter a consistência de postagem trabalhando em tempo integral?",
    likes: 71,
    publishedAt: "2026-02-23T15:45:00Z",
    replyCount: 8,
    authorReplied: true,
  },
  {
    id: "36",
    author: "Vinicius Motivação",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vinicius",
    text: "Bravo! Esse vídeo deveria ter mais views. YouTube precisa recomendar mais conteúdo assim.",
    likes: 156,
    publishedAt: "2026-02-24T07:00:00Z",
    replyCount: 3,
    authorReplied: true,
  },
  {
    id: "37",
    author: "Gabriela Moda",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Gabriela",
    text: "Qual câmera você usa para gravar? A qualidade de imagem está impecável.",
    likes: 48,
    publishedAt: "2026-02-24T09:30:00Z",
    replyCount: 4,
    authorReplied: true,
  },
  {
    id: "38",
    author: "Roberto Idoso",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto",
    text: "Conteúdo ok, nada demais. Já vi vídeos melhores sobre o assunto.",
    likes: 14,
    publishedAt: "2026-02-24T11:00:00Z",
    replyCount: 1,
    authorReplied: false,
  },
  {
    id: "39",
    author: "Daniela Yoga",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniela",
    text: "Amei demais! Já implementei o calendário editorial e minha produtividade triplicou.",
    likes: 102,
    publishedAt: "2026-02-24T14:00:00Z",
    replyCount: 2,
    authorReplied: false,
  },
  {
    id: "40",
    author: "Mateus Geek",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mateus",
    text: "Vale a pena pagar pelo YouTube Premium para testar conteúdo sem anúncios?",
    likes: 33,
    publishedAt: "2026-02-24T16:30:00Z",
    replyCount: 5,
    authorReplied: true,
  },
];

export const MOCK_COMMENTS: Comment[] = RAW_COMMENTS.map((c) => ({
  ...c,
  sentiment: analyzeSentiment(c.text),
}));

export function fetchMockComments(): Promise<{ video: VideoInfo; comments: Comment[] }> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({ video: MOCK_VIDEO, comments: MOCK_COMMENTS });
    }, 1200);
  });
}
