import type { LiveChatMessage, LiveStreamInfo } from "@/types";

export const MOCK_LIVE: LiveStreamInfo = {
  id: "live-2026-qa",
  title: "AO VIVO: tira-dúvidas — como crescer no YouTube em 2026",
  channelName: "Canal Criador Pro",
  channelAvatar:
    "https://api.dicebear.com/7.x/initials/svg?seed=CCP&backgroundColor=ef4444",
  thumbnailUrl:
    "https://images.unsplash.com/photo-1598488035139-4d3b0b56d0d6?w=640&h=360&fit=crop",
  concurrentViewers: 1840,
  startedAt: "2026-03-12T19:00:00Z",
};

type RawMessage = Omit<LiveChatMessage, "id" | "authorAvatar" | "isQuestion">;

const RAW: RawMessage[] = [
  { author: "Ana Silva", text: "Boa noite! Cheguei agora, essa live é ouro", isSuperChat: false, block: 0 },
  { author: "Pedro Games", text: "Fala galera, primeira live que pego ao vivo", isSuperChat: false, block: 0 },
  { author: "Lucas Tech", text: "Som está ótimo hoje", isSuperChat: false, block: 0 },
  { author: "Mariana Vlogs", text: "Assisti o vídeo de thumbnail ontem, mudei a minha já", isSuperChat: false, block: 0 },
  { author: "Thiago Iniciante", text: "Tenho 80 inscritos, vale a pena continuar?", isSuperChat: false, block: 0 },
  { author: "Beatriz Marketing", text: "Boa noite! Pergunta: como vocês escolhem o título?", isSuperChat: false, block: 0 },
  { author: "Julia Criativa", text: "Thumbnail faz tanta diferença assim mesmo?", isSuperChat: false, block: 0 },
  { author: "Carlos Editor", text: "Qual ferramenta vocês usam pra thumbnail? Canva ou Photoshop?", isSuperChat: false, block: 0 },
  { author: "Fernanda Lifestyle", text: "Minha thumbnail está fraca, CTR em 2%", isSuperChat: false, block: 0 },
  { author: "Diego Streamer", text: "Pessoal, thumbnail com rosto funciona melhor no meu nicho de games?", isSuperChat: false, block: 0 },
  {
    author: "Patrícia SEO",
    text: "R$ 20 — fala mais de thumbnail e contraste, por favor",
    isSuperChat: true,
    superChatAmount: "R$ 20",
    block: 0,
  },
  { author: "Bruno Filmmaker", text: "Contraste na thumbnail mudou meu CTR de 3% pra 7%", isSuperChat: false, block: 0 },
  { author: "Amanda Design", text: "Thumbnail com texto grande + rosto = ouro", isSuperChat: false, block: 0 },
  { author: "Helena Educação", text: "Tem template de thumbnail que você recomenda?", isSuperChat: false, block: 0 },
  { author: "João Pet", text: "Vou refazer todas as thumbnails essa semana", isSuperChat: false, block: 0 },
  { author: "Isabela Music", text: "E edição? Vocês usam CapCut ou Premiere?", isSuperChat: false, block: 1 },
  { author: "Felipe Automacao", text: "CapCut no celular dá conta de um canal pequeno?", isSuperChat: false, block: 1 },
  { author: "Larissa Beauty", text: "CapCut me salvou, edito tudo pelo celular", isSuperChat: false, block: 1 },
  { author: "André Fitness", text: "Premiere é overkill no começo, CapCut resolve", isSuperChat: false, block: 1 },
  { author: "Camila Coach", text: "Tem tutorial de CapCut no canal?", isSuperChat: false, block: 1 },
  { author: "Natália Parenting", text: "Quero um vídeo só de CapCut, cortes e legendas", isSuperChat: false, block: 1 },
  { author: "Eduardo Crypto", text: "CapCut + legendas automáticas acelerou minha edição", isSuperChat: false, block: 1 },
  { author: "Sofia Art", text: "Quanto tempo vocês gastam editando cada vídeo?", isSuperChat: false, block: 1 },
  { author: "Gabriela Moda", text: "CapCut tem aqueles templates de transição que viralizam?", isSuperChat: false, block: 1 },
  {
    author: "Renato Finanças",
    text: "R$ 50 — faz um vídeo de CapCut do zero, eu pago o café",
    isSuperChat: true,
    superChatAmount: "R$ 50",
    block: 1,
  },
  { author: "Vanessa Food", text: "E monetização? Com 1k inscritos já dá pra pedir?", isSuperChat: false, block: 2 },
  { author: "Marcos Dev", text: "Monetização YPP agora pede 500 inscritos e 3k watch hours?", isSuperChat: false, block: 2 },
  { author: "Carolina Travel", text: "Monetização no Brasil paga pouco no começo, é verdade?", isSuperChat: false, block: 2 },
  { author: "Ricardo Critic", text: "Foco em monetização cedo mata o canal, concordo", isSuperChat: false, block: 2 },
  { author: "Tatiane DIY", text: "Melhor caminho pra monetização: membros ou Super Chat?", isSuperChat: false, block: 2 },
  { author: "Vinicius Motivação", text: "Monetização veio no meu 4º mês, consistência vence", isSuperChat: false, block: 2 },
  { author: "Paula Idiomas", text: "Dá pra viver de monetização com canal em português?", isSuperChat: false, block: 2 },
  { author: "Leandro Review", text: "Patrocínio paga mais que monetização do Adsense aqui", isSuperChat: false, block: 2 },
  { author: "Daniela Yoga", text: "Como vocês fecham o primeiro patrocínio?", isSuperChat: false, block: 2 },
  { author: "Mateus Geek", text: "Shorts ajudam na monetização longa ou só infla inscrito?", isSuperChat: false, block: 3 },
  { author: "Felipe Automacao", text: "Faço Shorts todo dia e o longo não cresce, por quê?", isSuperChat: false, block: 3 },
  { author: "Isabela Music", text: "Shorts como funil pro vídeo longo funciona mesmo?", isSuperChat: false, block: 3 },
  { author: "Diego Streamer", text: "Meus Shorts bombam, o longo fica em 200 views", isSuperChat: false, block: 3 },
  { author: "Julia Criativa", text: "Quantos Shorts por semana vocês recomendam?", isSuperChat: false, block: 3 },
  { author: "Pedro Games", text: "Vou testar Shorts recortando o melhor momento da live", isSuperChat: false, block: 3 },
  { author: "Amanda Design", text: "Thumbnail nos Shorts? Ou o cover automático basta?", isSuperChat: false, block: 3 },
  { author: "Bruno Filmmaker", text: "Shorts + community post subiu meu inscrito essa semana", isSuperChat: false, block: 3 },
  {
    author: "Helena Educação",
    text: "R$ 10 — fala a frequência ideal de Shorts vs vídeo longo",
    isSuperChat: true,
    superChatAmount: "R$ 10",
    block: 3,
  },
  { author: "Gabriela Moda", text: "Qual câmera vocês usam nessa live?", isSuperChat: false, block: 4 },
  { author: "Carlos Editor", text: "Microfone faz mais diferença que câmera, né?", isSuperChat: false, block: 4 },
  { author: "Thiago Iniciante", text: "Celular serve pra gravar ou preciso de câmera já?", isSuperChat: false, block: 4 },
  { author: "João Pet", text: "Gravei 6 meses no celular, câmera veio depois", isSuperChat: false, block: 4 },
  { author: "Larissa Beauty", text: "Luz natural + celular ainda é o combo de ouro", isSuperChat: false, block: 4 },
  { author: "André Fitness", text: "Qual microfone barato vocês recomendam?", isSuperChat: false, block: 4 },
  { author: "Camila Coach", text: "Iluminação ring light ou softbox pra talking head?", isSuperChat: false, block: 4 },
  { author: "Natália Parenting", text: "Câmera boa não salva roteiro ruim", isSuperChat: false, block: 4 },
  { author: "Eduardo Crypto", text: "Próximo vídeo podia ser setup barato: celular, microfone e luz", isSuperChat: false, block: 4 },
  { author: "Sofia Art", text: "Essa live deveria virar um vídeo editado depois", isSuperChat: false, block: 5 },
  { author: "Renato Finanças", text: "Anotando tudo, vocês vão postar o recap?", isSuperChat: false, block: 5 },
  { author: "Vanessa Food", text: "Melhor live do canal, sério", isSuperChat: false, block: 5 },
  { author: "Marcos Dev", text: "Fazem live toda quinta?", isSuperChat: false, block: 5 },
  { author: "Carolina Travel", text: "Quero o roteiro dessa pauta, conteúdo demais", isSuperChat: false, block: 5 },
  { author: "Beatriz Marketing", text: "Obrigado! Vou aplicar thumbnail, CapCut e Shorts essa semana", isSuperChat: false, block: 5 },
  { author: "Patrícia SEO", text: "Fechando: consistência > equipamento. Recado dado", isSuperChat: false, block: 5 },
  {
    author: "Vinicius Motivação",
    text: "R$ 30 — valeu demais, melhor live de YouTube que já vi",
    isSuperChat: true,
    superChatAmount: "R$ 30",
    block: 5,
  },
  { author: "Ana Silva", text: "Valeu galera, até a próxima live", isSuperChat: false, block: 5 },
  { author: "Pedro Games", text: "Inscrevi agora, conteúdo top", isSuperChat: false, block: 5 },
];

export const MOCK_LIVE_MESSAGES: LiveChatMessage[] = RAW.map((m, i) => ({
  ...m,
  id: `live-${i + 1}`,
  authorAvatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(m.author)}`,
  isQuestion: m.text.includes("?"),
}));

export const LIVE_BLOCK_LABELS = [
  "Abertura",
  "Edição / CapCut",
  "Monetização",
  "Shorts",
  "Equipamento",
  "Encerramento",
];
